#!/usr/bin/env bash
# Script that configures Nginx server to redirect to another page

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create Sample page
echo "Hello World!" > /var/www/html/index.html

# Configure existing server block
sudo sed -i '/server_name _;/a \
\
    location \/redirect_me {\
        return 301 https:\/\/www.youtube.com;\
    }' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
