#!/usr/bin/env bash
# This script creates a PID file and displays messages on receiving signals.

pid_file="/var/run/myscript.pid"

trap 'rm -f $pid_file; exit' SIGQUIT SIGTERM

echo $$ > $pid_file
echo "To infinity and beyond"

while true; do
    sleep 2
done
