#!/usr/bin/env bash
# Get the PID of the current script

script_pid=$$
count=0

while read -r; do
    echo "$script_pid bash"
    ((count++))
    
    if [ $count -eq 2 ]; then
        break
    fi
done < <(pgrep -f bash)
