#!/usr/bin/env bash

# Get the PID of the current script
script_pid=$$

# Get the PIDs and process names of all processes containing the word "bash"
while read -r pid name; do
    echo "$pid $name"
done < <(pgrep -f bash)
