#!/usr/bin/env bash
# This script stops the process created by 4-to_infinity_and_beyond without using kill.

# Use pgrep to find the process ID and send SIGTERM signal to the first match
kill -SIGTERM "$(pgrep -f "To infinity and beyond" | head -n 1)"
