#!/usr/bin/env bash
# This script displays relevant information from the /etc/passwd file.

while IFS=':' read -r username x uid gid info home shell; do
  echo "$username:$uid:$home"
done < /etc/passwd
