#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using a while loop.

hour=0

while [ $hour -le 12 ]; do
    if [ $hour -eq 1 ]; then
        echo "Hour: $hour"
    fi
    
    minute=0
    while [ $minute -le 59 ]; do
        if [ $hour -eq 0 ] && [ $minute -ge 1 ]; then
            echo $minute
        elif [ $hour -eq 1 ]; then
            echo $minute
        fi
        ((minute++))
    done

    ((hour++))
done
