#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

for ((hour=0; hour<=12; hour++)); do
  echo "Hour: $hour"
  for ((minute=1; minute<=59; minute++)); do
    echo $minute
  done
done
