#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to display active IPv4 IPs and filter using awk
ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v "127.0.0.1"
